
services:
  api:
    build: .
    container_name: orders_api
    ports:
      - "3000:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:15
    container_name: orders_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: orders_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  